We can see this in the above example. If you tried evaluating (1 1 +), you would get an exception.
